### ISSUE TITLE
IOError raised in flush should display status code

### ISSUE THREAD

**Issue by julienbachmann** [librato/python-librato#105]
Hello,

I have sometime IOError that is raised when I flush. But the problem is that in the IOError object I just have a text that don't tell me what was the problem.

Here is the stacktrace I have:

    Traceback (most recent call last):
      File "/home/eee/anaconda/envs/eee/bin/zibrato-librato", line 9, in <module>
        load_entry_point('Zibrato==0.2.0', 'console_scripts', 'zibrato-librato')()
      File "/home/eee/anaconda/envs/eee/lib/python2.7/site-packages/zibrato/librato.py", line 106, in main
        l.flush()
      File "/home/eee/anaconda/envs/eee/lib/python2.7/site-packages/zibrato/librato.py", line 70, in flush
        raise IOError(r.text + ' ' + data)
    IOError:  {"gauges": [{"name": "engine-time-engine_2", "value": 203.0, "source":     "dev:eee:1.internal", "measure_time": "1446481740"}, {"name": "engine-time-    default", "value": 122.0, "source": "dev:eee:1.internal", "measure_time":     "1446481800"}]}

The code in python-librato that raise this error is as follow:

      if r.status_code > 200 :
        raise IOError(r.text + ' ' + data)
      else:
        return r.status_code

As you can see, this does not tell me what was wrong. If I would have the status code it will help me to understand.

**Comment by drio** [comment]
Hi @julienbachmann, 

It seems the zibrato project uses its own code to interact with our API. You should be able to get the API error from [requests](http://docs.python-requests.org/en/latest/) and get a better understanding of why this is failing.

Please, keep me posted.

**Comment by julienbachmann** [comment]
Sorry, I was thinking librato.py was in your lib. I didn't notice that it was in zibrato project.

Sorry for that.
