### ISSUE TITLE
Invalid key `type`

### ISSUE THREAD

**Issue by bowillyard** [librato/python-librato#106]
Nov 23 13:29:16 jackdaw-prod-1 jackdaw-log:  WARN  [2015-11-23 19:29:15,562] com.librato.jackdaw.codec.InvalidParameter: <email redacted>[python-librato] Invalid key `type`

queue.py line 53 ==>nm['type'] = type

I think that this line should be removed

**Comment by josephruscio** [comment]
cc @drio @jderrett

**Comment by drio** [comment]
@bowillyard `type` is a valid parameter for that endpoint (http://dev.librato.com/v1/put/metrics/:name). Can you please provide the context in which this is failing?

**Comment by bowillyard** [comment]
This is in queue.py and that uses POST

   def submit(self):
        empty_chunks = [self._gen_empty_chunk()]
        if self.chunks == empty_chunks:
            return
        for c in self.chunks:
            self.connection._mexe("metrics", method="POST", query_props=c)
        self.chunks = empty_chunks

I am using this in the librato-python-web for the django integration.   I am seeing warnings in the papertrail logs.

Nov 24 08:00:20 jackdaw-prod-2 jackdaw-log:  WARN 2015-11-24 14:00:11,868 [dw-754 - POST /v1/metrics] c.l.j.c.InvalidParameter: [iris-notifications@solarwinds.com][python-librato] Invalid key `type`

**Comment by jderrett** [comment]
I think we can remove this line of code - `type` is indeed an invalid key but the payloads are still accepted by the API.  Basically everyone using python-librato will have messages like this in our logs.  Thanks for the catch @bowillyard.

**Comment by jderrett** [comment]
Resolved in #108
