### ISSUE TITLE
Service class, add title and type

### ISSUE THREAD

**Issue by kaidokert** [librato/python-librato#111]
Currently Service class only retains the ID attribute, and discards 'title' and 'type'. This is mostly fine for defining alerts, but a bit annoying for introspection. For instance, if you want to pull a list of alerts to make sure they are all enabled for particular reporting service. 
Alternatively, being able to list the available services from /v1/services with full data would help, too.

**Comment by josephruscio** [comment]
@kaidokert thanks for opening this issue! We'll look to figure out the best way to address this.

**Comment by jderrett** [comment]
Addressing this in #117
