### ISSUE TITLE
Add support for Spaces

### ISSUE THREAD

**Issue by earthican** [librato/python-librato#112]
https://www.librato.com/docs/api/#spaces

**Comment by josephruscio** [comment]
@earthican wow thanks for taking a stab at this! Will have the team review and provide any necessary feedback next week :) cc @drio @jderrett @vaidy4github

**Comment by earthican** [comment]
just an update, still working on it, creating test cases and such. sorry for the lag :smile_cat:

**Comment by earthican** [comment]
#113

**Comment by jderrett** [comment]
Working in #114

**Comment by jderrett** [comment]
Released in #114 as version `1.0.0`
