### ISSUE TITLE
Python bug sending tags from queue

### ISSUE THREAD

**Issue by mtanski** [librato/python-librato#170]
It looks like there's a bug in the code at: https://github.com/librato/python-librato/blob/master/librato/queue.py#L139

```c['tags'] = dict(self.tags).update(c['tags'])```

__dict__.update function does not return anything (None) so it overwrites c['tags'] with None

**Comment by jderrett** [comment]
@mtanski thanks very much for the bug report. We'll see about getting this fixed shortly.

**Comment by mbeale** [comment]
@mtanski good point.  I'll update the code. I think the following will do it:

```
c['tags'] = dict(dict(self.tags), **c['tags'])
```

**Comment by mbeale** [comment]
This is addressed in https://github.com/librato/python-librato/pull/172
