### ISSUE TITLE
get does not accept composite metrics

### ISSUE THREAD

**Issue by edechter** [librato/python-librato#57]
The (get method)[https://github.com/librato/python-librato/blob/master/librato/__init__.py#L187] does not accept the `compose` parameter, because it requires a `name` argument. 

I could provide a patch but the api doesn't specify what to expect in the response to a compose request so I don't know how to set up `Guage` or `Counter` object given such a response.

**Comment by jderrett** [comment]
@mauricioborges no problem, but this issue doesn't actually address setting up instruments with composite streams.  This is referring to querying data back as a composite.  So, #77 doesn't close this issue - we'll treat it separately.
