### ISSUE TITLE
add support to create composite metrics

### ISSUE THREAD

**Issue by mauricioborges** [librato/python-librato#87]
Hi there,

Actually I haven't seen this being documented on http://dev.librato.com/v1/metrics, so I'm in doubt if it is officially supported. I'd like to persist composite metrics through this client.

**Comment by nextmat** [comment]
@mauricioborges We definitely support it through the api, [here are the docs for that](http://dev.librato.com/v1/put/metrics/:name). Do we have support in this client yet @jderrett ?

**Comment by jderrett** [comment]
@mauricioborges @nextmat we do not yet have support for persisted composite metrics in this library, but we do have basic support for composites on the fly.  Maybe something @drio would be interested in adding?

**Comment by drio** [comment]
Absolutely. I'll work on it.

**Comment by drio** [comment]
@mauricioborges We pushed a new release that implements what you requested. Now you can do:

```python
  api.create_composite('humidity', 'sum(s("all.*", "*"))', description="a test composite") 
```
Let us know if you need something else.

**Comment by mauricioborges** [comment]
awesome! many thanks. Actually I'd start working on it today  but you were
all fast :p. I'll give it a try
