### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by marcelocure** [librato/python-librato#98]
Hi @drio ,

I want to collaborate on python-librato.
I've finished https://github.com/librato/python-librato/issues/54

However I need permission to push it.

Can you give me permission?

**Comment by josephruscio** [comment]
@marcelocure awesome to see you hacking on this! Could you submit a pull request for #54? If it looks good we can merge it in.

**Comment by marcelocure** [comment]
It seems I need permission on it.

marcelocure@marcelocure:~/github/python-librato$ git push origin annotationUnitTests54 
ERROR: Permission to librato/python-librato.git denied to marcelocure.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by josephruscio** [comment]
@marcelocure if you fork this repo you should be able to push your branch to your fork, and then submit a pull request from your fork to our upstream. You can find Github's instructions here: https://help.github.com/articles/using-pull-requests/

**Comment by marcelocure** [comment]
Ohh yeah, I just cloned it. I'll fork and submit it. Sorry by The confusion. Tomorrow morning I'll do it. Thanks
